/* ============================================================
   GIA PHẢ LÊ QUANG — DỮ LIỆU
   Cách sửa: thêm/sửa một dòng người bên dưới.
   Các trường:
     id      : mã duy nhất (không dấu, không khoảng trắng)
     name    : tên chính thức (tên húy)
     alias   : tên gọi khác, ví dụ "Sáu Lý"
     g       : "m" = nam, "f" = nữ
     gen     : đời thứ (số)
     chi     : chi (1..6) — chỉ ghi cho người đứng đầu chi
     parents : [id cha, id mẹ] (có thể bỏ trống)
     spouses : [id vợ/chồng]
     years   : năm sinh–mất (nếu biết)
     phone   : số điện thoại (để trống nếu không có)
     address : địa chỉ
     email   : email
     birth   : năm sinh (chỉ năm)
     death   : năm mất
     place   : quê quán / nơi ở
     job     : nghề nghiệp
     story   : tiểu sử ngắn, chuyện kể
     note    : ghi chú
   Những chỗ ghi "cần xác nhận" trong note là các quan hệ
   suy đoán từ sơ đồ drawio — gia đình nên rà soát lại.
   ============================================================ */
const PEOPLE = [
  // ĐỜI 1–2
  { id:"dai", name:"LÊ QUANG ĐẠI", g:"m", gen:1 },
  { id:"mau", name:"LÊ QUANG MẬU", g:"m", gen:2, parents:["dai"] },
  { id:"ve",  name:"LÊ QUANG VỆ",  g:"m", gen:2, parents:["dai"], spouses:["du"] },

  // ĐỜI 3
  { id:"vanluong", name:"Ông tước VĂN LƯƠNG", g:"m", gen:3, parents:["mau"] },
  { id:"quyt", name:"Ông QUÝT", g:"m", gen:3, parents:["mau"] },
  { id:"locbahau", name:"Ông tước LỘC BÁ HẦU", g:"m", gen:3, parents:["mau"] },
  { id:"so",   name:"Ông SỞ",   g:"m", gen:3, parents:["ve"], spouses:["chuc"] },
  { id:"du",   name:"Bà tổng DỤ", g:"f", gen:3, spouses:["ve"] },
  { id:"chuc", name:"Bà CHỨC", g:"f", gen:3, spouses:["so"] },

  // ĐỜI 4
  { id:"toan",  name:"Ông sinh đồ TOAN", alias:"tên húy VĂN NGHI", g:"m", gen:4, parents:["vanluong"] },
  { id:"y",     name:"Ông Ý",     g:"m", gen:4, parents:["quyt"] },
  { id:"lam",   name:"Ông LÂM",   g:"m", gen:4, parents:["quyt"] },
  { id:"lam2",  name:"Ông LẪM",   g:"m", gen:4, parents:["quyt"] },
  { id:"ni",    name:"Ông NI",    g:"m", gen:4, parents:["so"] },
  { id:"trung", name:"Ông TRUNG", g:"m", gen:4, parents:["so"] },
  { id:"nghi",  name:"Ông NGHỊ",  g:"m", gen:4, parents:["so"] },
  { id:"nghe",   name:"Bà NGHÉ",   g:"f", gen:4, parents:["du"] },
  { id:"trong",  name:"Bà TRONG",  g:"f", gen:4, parents:["chuc"] },
  { id:"nghiem", name:"Bà NGHIÊM", g:"f", gen:4, parents:["chuc"] },
  { id:"thanh",  name:"Bà THANH",  g:"f", gen:4, parents:["chuc"] },

  // ĐỜI 5
  { id:"ky",    name:"Ông KỴ",    g:"m", gen:5, parents:["toan"] },
  { id:"dat",   name:"Ông ĐẠT",   g:"m", gen:5, parents:["toan"] },
  { id:"dien",  name:"Ông ĐIỆN",  g:"m", gen:5, parents:["toan"] },
  { id:"u",     name:"Ông Ừ (ỪA)", alias:"tên húy VĂN PHỐI", g:"m", gen:5, parents:["lam2"] },
  { id:"cuong", name:"Ông CƯƠNG", g:"m", gen:5, parents:["ni"] },
  { id:"tac",   name:"Ông TẮC",   g:"m", gen:5, parents:["trung"] },
  { id:"hao",   name:"Ông HÀO",   g:"m", gen:5, parents:["nghi"], spouses:["ngoa"] },
  { id:"ngoa",  name:"Bà NGÕA",   g:"f", gen:5, spouses:["hao"] },
  { id:"bao",   name:"Bà BẢO",    g:"f", gen:5, spouses:[], note:"Mẹ của LÊ QUANG THƠ; chồng chưa ghi trên sơ đồ." },

  // ĐỜI 6
  { id:"tam",   name:"Ông TÂM",   g:"m", gen:6, parents:["ky"] },
  { id:"trach", name:"Ông TRẠCH", g:"m", gen:6, parents:["dat"] },
  { id:"dien2", name:"Ông DIỄN",  g:"m", gen:6, parents:["dien"] },
  { id:"bai",   name:"Ông BÁI",   g:"m", gen:6, parents:["u"] },
  { id:"luu",   name:"Ông LỮ",    g:"m", gen:6, parents:["u"] },
  { id:"haof",  name:"Bà HẢO",    g:"f", gen:6, parents:["cuong"] },
  { id:"loi",   name:"Bà LỖI",    g:"f", gen:6, parents:["tac"] },
  { id:"kieu",  name:"Bà KIỀU",   g:"f", gen:6, parents:["hao"] },
  { id:"tho6",  name:"LÊ QUANG THƠ", alias:"Ông xã THƯ", g:"m", gen:6, parents:["bao"], spouses:["huong"], note:"Mẹ là Bà BẢO; cha chưa ghi trên sơ đồ." },
  { id:"huong", name:"NGUYỄN THỊ HƯỚNG", g:"f", spouses:["tho6"] },

  // ĐỜI 7 — con của LÊ QUANG THƠ
  { id:"xuan",     name:"LÊ QUANG XUÂN", alias:"trùm QUÁ", g:"m", gen:7, parents:["tho6"] },
  { id:"linhtuan", name:"LÊ QUANG LÍNH TUÂN", g:"m", gen:7, parents:["tho6"] },
  { id:"thung",    name:"LÊ QUANG THUNG", g:"m", gen:7, parents:["tho6"] },
  { id:"trovan",   name:"LÊ QUANG TRÒ VĂN", g:"m", gen:7, parents:["tho6"] },
  { id:"linhtin",  name:"LÊ QUANG LÍNH TÍN", g:"m", gen:7, parents:["tho6"] },
  { id:"chaxa",    name:"LÊ QUANG CHA XẠ", g:"m", gen:7, parents:["tho6"] },
  { id:"tuy",      name:"LÊ QUANG TUY", g:"m", gen:7, parents:["tho6"] },
  { id:"nghiem2",  name:"LÊ QUANG NGHIÊM", g:"m", gen:7, parents:["tho6"] },
  { id:"thuc",  name:"LÊ THỊ THỨC", g:"f", gen:7, parents:["tho6"] },
  { id:"biem",  name:"LÊ THỊ BIỆN", g:"f", gen:7, parents:["tho6"] },
  { id:"diem1", name:"LÊ THỊ ĐIỂM", g:"f", gen:7, parents:["tho6"] },
  { id:"diem2", name:"LÊ THỊ ĐIỀM", g:"f", gen:7, parents:["tho6"] },
  { id:"dung2", name:"LÊ THỊ DUNG", g:"f", gen:7, parents:["tho6"] },
  { id:"thoa",  name:"LÊ THỊ THỎA", g:"f", gen:7, parents:["tho6"] },

  // ĐỜI 8 — con của LÊ QUANG XUÂN
  { id:"qua",   name:"LÊ QUANG QUÁ", alias:"Trưởng Tuyển", g:"m", gen:8, parents:["xuan"] },
  { id:"toan3", name:"LÊ QUANG TOÃN", g:"m", gen:8, parents:["xuan"] },
  { id:"dieu",  name:"LÊ QUANG ĐIỆU", g:"m", gen:8, parents:["xuan"] },
  { id:"vien",  name:"LÊ QUANG VIÊN", g:"m", gen:8, parents:["xuan"] },
  { id:"chau", name:"LÊ THỊ CHÂU", g:"f", gen:8, parents:["xuan"] },
  { id:"tan1", name:"LÊ THỊ TÁN",  g:"f", gen:8, parents:["xuan"] },
  { id:"lam1", name:"LÊ THỊ LÂM",  g:"f", gen:8, parents:["xuan"] },

  // ĐỜI 9 — con của LÊ QUANG QUÁ
  { id:"ngoan", name:"LÊ QUANG NGOAN", alias:"Thông Hương", g:"m", gen:9, parents:["qua"], spouses:["lan"] },
  { id:"lan",   name:"NGUYỄN THỊ LAN", g:"f", spouses:["ngoan"] },
  { id:"quang", name:"LÊ QUANG QUẢNG", g:"m", gen:9, parents:["qua"] },
  { id:"phach", name:"LÊ QUANG PHÁCH", g:"m", gen:9, parents:["qua"] },
  { id:"ta",  name:"LÊ THỊ TẠ",  g:"f", gen:9, parents:["qua"] },
  { id:"lai", name:"LÊ THỊ LẠI", g:"f", gen:9, parents:["qua"] },

  // ĐỜI 10 — con của LÊ QUANG NGOAN
  { id:"tien", name:"LÊ QUANG TIẾN", alias:"Thông Tiến", g:"m", gen:10, parents:["ngoan"] },
  { id:"quy1", name:"LÊ THỊ QUÝ (QUỚI)", g:"f", gen:10, parents:["ngoan"], note:"Con gái hay vợ — cần xác định." },

  // ĐỜI 11 — con của LÊ QUANG TIẾN
  { id:"cau",   name:"LÊ QUANG CÂU (CU)", g:"m", gen:11, parents:["tien"], spouses:["si"] },
  { id:"si",    name:"LÊ THỊ SỈ", g:"f", spouses:["cau"], note:"Cặp đôi cần xác nhận." },
  { id:"vi",    name:"LÊ QUANG VỊ", g:"m", gen:11, parents:["tien"], spouses:["tan2","la"] },
  { id:"tan2",  name:"LÊ THỊ TẤN (TIẾN)", g:"f", spouses:["vi"], note:"Cặp đôi cần xác nhận." },
  { id:"la",    name:"LÊ THỊ LẠ (HÀ)", g:"f", spouses:["vi"] },
  { id:"huop",  name:"LÊ QUANG HƯỢP (HẠT)", g:"m", gen:11, parents:["tien"] },
  { id:"hue",   name:"LÊ QUANG HUỀ", g:"m", gen:11, parents:["tien"] },
  { id:"dau",   name:"LÊ QUANG ĐẤU", g:"m", gen:11, parents:["tien"], spouses:["khanh"] },
  { id:"khanh", name:"LÊ THỊ KHANH", g:"f", spouses:["dau"] },
  { id:"thai",  name:"LÊ QUANG THÁI", g:"m", gen:11, parents:["tien"] },
  { id:"vien2", name:"LÊ QUANG VIỄN", g:"m", gen:11, parents:["tien"] },
  { id:"thong", name:"LÊ QUANG THÔNG", alias:"Quang Minh", g:"m", gen:11, parents:["tien"], chi:1 },
  { id:"buu",   name:"LÊ QUANG BỬU", g:"m", gen:11, parents:["tien"], note:"Chi chưa xác định." },
  { id:"giai",  name:"LÊ QUANG GIAI", g:"m", gen:11, parents:["tien"], chi:2, spouses:["khuong"] },
  { id:"khuong",name:"LÊ THỊ KHƯƠNG", g:"f", spouses:["giai"] },
  { id:"canh",  name:"LÊ QUANG CẢNH", g:"m", gen:11, parents:["tien"], chi:3, spouses:["tiep"] },
  { id:"tiep",  name:"LÊ THỊ TIẾP", g:"f", spouses:["canh"] },
  { id:"toan2", name:"LÊ QUANG TOÀN", g:"m", gen:11, parents:["tien"], chi:5, spouses:["tuong"] },
  { id:"tuong", name:"LÊ THỊ TƯỚNG", g:"f", spouses:["toan2"] },
  { id:"muoi",  name:"LÊ THỊ MƯỜI", g:"f", gen:11, parents:["tien"] },
  { id:"phuoc", name:"LÊ QUANG PHƯỚC", g:"m", gen:11, parents:["tien"], chi:6 },
  { id:"ly",    name:"LÊ QUANG LÝ", alias:"Sáu Lý", g:"m", gen:11, parents:["tien"] },
  { id:"chi",   name:"LÊ QUANG CHỈ", alias:"Bảy Chỉ", g:"m", gen:11, parents:["tien"] },

  // ĐỜI 12 — con của LÊ QUANG THÔNG (CHI 1)
  { id:"dinh",  name:"LÊ QUANG ĐỆ", g:"m", gen:12, parents:["thong"] },
  { id:"huu",   name:"LÊ QUANG HỮU", g:"m", gen:12, parents:["thong"], spouses:["dung3"] },
  { id:"dung3", name:"LÊ THỊ DUNG", g:"f", spouses:["huu"] },
  { id:"tho",   name:"LÊ QUANG THỌ", alias:"Cử nhân Diệu", g:"m", gen:12, parents:["thong"] },
  { id:"huy",   name:"LÊ QUANG HUY", g:"m", gen:12, parents:["thong"] },
  { id:"triet", name:"LÊ QUANG TRIẾT", g:"m", gen:12, parents:["thong"], spouses:["chieu"] },
  { id:"chieu", name:"LÊ THỊ CHIÊU", g:"f", spouses:["triet"] },
  { id:"thinh", name:"LÊ QUANG THỊNH", g:"m", gen:12, parents:["thong"], spouses:["phong"] },
  { id:"phong", name:"LÊ THỊ PHONG", g:"f", spouses:["thinh"], note:"Cặp đôi cần xác nhận." },
  { id:"chien12", name:"LÊ QUANG CHIẾN", g:"m", gen:12, parents:["thong"], chi:4 },
  { id:"nhuan", name:"LÊ QUANG NHUẬN", g:"m", gen:12, parents:["thong"] },

  // ĐỜI 13 — con của LÊ QUANG THỌ
  { id:"chan",    name:"LÊ QUANG CHẤN", g:"m", gen:13, parents:["tho"], spouses:["tho1"] },
  { id:"tho1",    name:"LÊ THỊ THỌ", g:"f", spouses:["chan"] },
  { id:"tienhoc", name:"LÊ QUANG TIÊN (HỌC)", alias:"Học", g:"m", gen:13, parents:["tho"], spouses:["hothisu"], years:"1866–1935" },
  { id:"hothisu", name:"HỒ THỊ SỬ", g:"f", spouses:["tienhoc"], years:"1871–1953" },
  { id:"doi",     name:"LÊ QUANG ĐỐI", g:"m", gen:13, parents:["tho"], spouses:["ky1"] },
  { id:"ky1",     name:"LÊ THỊ KỶ", g:"f", spouses:["doi"], note:"Cặp đôi cần xác nhận." },
  { id:"pho",     name:"LÊ QUANG PHỔ", g:"m", gen:13, parents:["tho"], spouses:["ha1"] },
  { id:"ha1",     name:"LÊ NGỌC HÀ", g:"f", spouses:["pho"], note:"Cặp đôi cần xác nhận." },
  { id:"phieu",   name:"LÊ QUANG PHIẾU", g:"m", gen:13, parents:["tho"], spouses:["chau1"] },
  { id:"chau1",   name:"LÊ NGỌC CHÂU", g:"f", spouses:["phieu"], note:"Cặp đôi cần xác nhận." },
  { id:"te",      name:"LÊ THỊ TẾ", g:"f", gen:13, parents:["tho"], note:"Vợ/chồng chưa xác định." },
  { id:"vodanh",  name:"LÊ vô danh", g:"m", gen:13, parents:["tho"], spouses:["huongcu"] },
  { id:"huongcu", name:"LÊ THỊ HƯỚNG CỬ", g:"f", spouses:["vodanh"] },

  // ĐỜI 14
  { id:"tan",   name:"LÊ QUANG TÁN", g:"m", gen:14, parents:["tienhoc","ky1"], spouses:["toan1"] },
  { id:"toan1", name:"LÊ THỊ TOÀN (TOÀ)", g:"f", spouses:["tan"], note:"Cặp đôi cần xác nhận." },
  { id:"nhi",   name:"LÊ QUANG NHÌ", g:"m", gen:14, parents:["tienhoc","ky1"], spouses:["du2"] },
  { id:"du2",   name:"LÊ NGỌC DỮ", g:"f", spouses:["nhi"], note:"Cặp đôi cần xác nhận." },
  { id:"tam",   name:"LÊ QUANG TAM", g:"m", gen:14, parents:["pho","ha1"], spouses:["luan1"] },
  { id:"luan1", name:"LÊ THỊ LUÂN", g:"f", spouses:["tam"], note:"Cặp đôi cần xác nhận." },
  { id:"hieu1904", name:"Nguyễn Thị Hiếu", g:"f", spouses:["tan"], years:"1904–1982" },
  { id:"viem1907", name:"Bùi Thị Viễn", g:"f", spouses:["nhi"], years:"1907–1971" },
  { id:"cuc1915", name:"Phan Thị Cúc", g:"f", spouses:["tam"], years:"1915–2008" },

  // ===== ĐỜI 15–19: con cháu của TÁN, NHÌ, TAM =====
  // (trích tự động từ Family-LeQuang-Tán-Nhì-Tam.drawio)
  { id:"lethiroan1930", name:"Lê Thị Roan", g:"f", gen:15, parents:["tan"], spouses:["phamky1922"], years:"1930" },
  { id:"phamky1922", name:"Phạm Kỹ", g:"m", gen:15, spouses:["lethiroan1930"], years:"1922" },
  { id:"lequangthang1935", name:"Lê Quang Thăng", g:"m", gen:15, parents:["tan"], spouses:["nguyenthivinhx"], years:"1935" },
  { id:"nguyenthivinhx", name:"Nguyễn Thị Vinh", g:"f", gen:15, spouses:["lequangthang1935"] },
  { id:"lequangtai1927", name:"Lê Quang Tại", g:"m", gen:15, parents:["tan"], spouses:["tranthibien1930"], years:"1927" },
  { id:"tranthibien1930", name:"Trần Thị Biền", g:"f", gen:15, spouses:["lequangtai1927"], years:"1930" },
  { id:"lethihaiduongx", name:"Lê Thị Hải Đường", g:"f", gen:15, parents:["tan"], spouses:["nguyenhoanhx"] },
  { id:"nguyenhoanhx", name:"Nguyễn Hoành", g:"m", gen:15, spouses:["lethihaiduongx"] },
  { id:"lethihuong1931", name:"Lê Thị Hương", g:"f", gen:15, parents:["tan"], spouses:["taminhcong1939"], years:"1931" },
  { id:"taminhcong1939", name:"Tạ Minh Công", g:"m", gen:15, spouses:["lethihuong1931"], years:"1939" },
  { id:"lequangbao1923", name:"Lê Quang Bão", g:"m", gen:15, parents:["tan"], spouses:["nguyenthidan1925"], years:"1923" },
  { id:"nguyenthidan1925", name:"Nguyễn Thị Dần", g:"f", gen:15, spouses:["lequangbao1923"], years:"1925" },
  { id:"tathisuong1964", name:"Tạ Thị Sương", g:"f", gen:16, parents:["lethihuong1931"], spouses:["nguyenhuuvinh1962"], years:"1964" },
  { id:"nguyenhuuvinh1962", name:"Nguyễn Hữu Vĩnh", g:"m", gen:16, spouses:["tathisuong1964"], years:"1962" },
  { id:"lequangngon1966", name:"Lê Quang Ngôn", g:"m", gen:16, parents:["lequangtai1927"], spouses:["nguyenthihongphuong1975"], years:"1966" },
  { id:"nguyenthihongphuong1975", name:"Nguyễn Thị Hồng Phương", g:"f", gen:16, spouses:["lequangngon1966"], years:"1975" },
  { id:"lequangtan1992", name:"Lê Quang Tân", g:"m", gen:17, parents:["tan"], spouses:["nguyenlethuytrang1999"], years:"1992" },
  { id:"nguyenlethuytrang1999", name:"Nguyễn Lê Thùy Trang", g:"f", gen:17, spouses:["lequangtan1992"], years:"1999" },
  { id:"lequangtoan1954", name:"Lê Quang Toàn", g:"m", gen:16, parents:["lequangbao1923"], spouses:["tranthithanhtam1956"], years:"1954" },
  { id:"tranthithanhtam1956", name:"Trần Thị Thanh Tâm", g:"f", gen:16, spouses:["lequangtoan1954"], years:"1956" },
  { id:"lethihue1956", name:"Lê Thị Huê", g:"f", gen:16, parents:["lequangbao1923"], spouses:["phamdao1957"], years:"1956" },
  { id:"phamdao1957", name:"Phạm Đạo", g:"m", gen:16, spouses:["lethihue1956"], years:"1957" },
  { id:"lethituongvy1954", name:"Lê Thị Tường Vy", g:"f", gen:16, parents:["lequangbao1923"], spouses:["nguyenchinh1946"], years:"1954" },
  { id:"nguyenchinh1946", name:"Nguyễn Chính", g:"m", gen:16, spouses:["lethituongvy1954"], years:"1946" },
  { id:"lethikimtuyen1955", name:"Lê Thị Kim Tuyến", g:"f", gen:16, parents:["lequangtai1927"], spouses:["tonthatminh1942"], years:"1955" },
  { id:"tonthatminh1942", name:"Tôn Thất Minh", g:"m", gen:16, spouses:["lethikimtuyen1955"], years:"1942–1992" },
  { id:"lequangcong1957", name:"Lê Quang Công", g:"m", gen:16, parents:["lequangtai1927"], spouses:["lathianhtram1965"], years:"1957" },
  { id:"lathianhtram1965", name:"Lã Thị Anh Trâm", g:"f", gen:16, spouses:["lequangcong1957"], years:"1965" },
  { id:"lequanghanh1968", name:"Lê Quang Hạnh", g:"m", gen:16, parents:["lequangtai1927"], spouses:["nguyenthiphuong1975"], years:"1968" },
  { id:"nguyenthiphuong1975", name:"Nguyễn Thị Phượng", g:"f", gen:16, spouses:["lequanghanh1968"], years:"1975" },
  { id:"phamngocliem1954", name:"Phạm Ngọc Liêm", g:"m", gen:16, parents:["lethiroan1930"], years:"1954–1972" },
  { id:"phamthithanhcan1957", name:"Phạm Thị Thanh Cần", g:"f", gen:16, parents:["lethiroan1930"], spouses:["phanvandinh1950"], years:"1957" },
  { id:"phanvandinh1950", name:"Phan Văn Định", g:"m", gen:16, spouses:["phamthithanhcan1957"], years:"1950" },
  { id:"phamthidiep1950", name:"Phạm Thị Diệp", g:"f", gen:16, parents:["lethiroan1930"], spouses:["phamtancanh1949"], years:"1950" },
  { id:"phamtancanh1949", name:"Phạm Tấn Cảnh", g:"m", gen:16, spouses:["phamthidiep1950"], years:"1949–2019" },
  { id:"phamthithanhhoa1962", name:"Phạm Thị Thanh Hoa", g:"f", gen:16, parents:["lethiroan1930"], spouses:["ledinhtruoc1955"], years:"1962" },
  { id:"ledinhtruoc1955", name:"Lê Đình Trước", g:"m", gen:16, spouses:["phamthithanhhoa1962"], years:"1955–2013" },
  { id:"phamthihoasen1962", name:"Phạm Thị Hoa Sen", g:"f", gen:16, parents:["lethiroan1930"], spouses:["buingocbinh1959"], years:"1962" },
  { id:"buingocbinh1959", name:"Bùi Ngọc Bình", g:"m", gen:16, spouses:["phamthihoasen1962"], years:"1959" },
  { id:"phamthithu1965", name:"Phạm Thị Thu", g:"f", gen:16, parents:["lethiroan1930"], spouses:["nguyendan1958"], years:"1965" },
  { id:"nguyendan1958", name:"Nguyễn Dân", g:"m", gen:16, spouses:["phamthithu1965"], years:"1958" },
  { id:"phamthikhanh1968", name:"Phạm Thị Khánh", g:"f", gen:16, parents:["lequangthang1935"], spouses:["caohoaimanh1968"], years:"1968" },
  { id:"caohoaimanh1968", name:"Cao Hoài Mạnh", g:"m", gen:16, spouses:["phamthikhanh1968"], years:"1968" },
  { id:"phamthithanhthuy1970", name:"Phạm Thị Thanh Thúy", g:"f", gen:16, parents:["lequangthang1935"], spouses:["lemykhoa1965"], years:"1970" },
  { id:"lemykhoa1965", name:"Lê Mỹ Khoa", g:"m", gen:16, spouses:["phamthithanhthuy1970"], years:"1965" },
  { id:"lequanglong1976", name:"Lê Quang Long", g:"m", gen:16, parents:["lequangthang1935"], spouses:["vothingoctrinh1978"], years:"1976" },
  { id:"vothingoctrinh1978", name:"Võ Thị Ngọc Trinh", g:"f", gen:16, spouses:["lequanglong1976"], years:"1978" },
  { id:"lehoangyen1974", name:"Lê Hoàng Yến", g:"f", gen:16, parents:["lequangthang1935"], spouses:["truongcongviet1973"], years:"1974" },
  { id:"truongcongviet1973", name:"Trương Công Việt", g:"m", gen:16, spouses:["lehoangyen1974"], years:"1973" },
  { id:"bachlam1969", name:"Bạch Lâm", g:"m", gen:16, parents:["lethihuong1931"], spouses:["lethiduyen1972"], years:"1969" },
  { id:"lethiduyen1972", name:"Lê Thị Duyên", g:"f", gen:16, spouses:["bachlam1969"], years:"1972" },
  { id:"nguyenbichhung1977", name:"Nguyễn Bích Hưng", g:"m", gen:16, parents:["lethihaiduongx"], spouses:["nguyenthithuha1981"], years:"1977" },
  { id:"nguyenthithuha1981", name:"Nguyễn Thị Thu Hà", g:"f", gen:16, spouses:["nguyenbichhung1977"], years:"1981" },
  { id:"nguyenbichvan1975", name:"Nguyễn Bích Vân", g:"f", gen:16, parents:["lethihaiduongx"], spouses:["lehonggiang1969"], years:"1975" },
  { id:"lehonggiang1969", name:"Lê Hồng Giang", g:"m", gen:16, spouses:["nguyenbichvan1975"], years:"1969" },
  { id:"nguyenbichha1968", name:"Nguyễn Bích Hà", g:"m", gen:16, parents:["lethihaiduongx"], spouses:["lydinchan1969"], years:"1968" },
  { id:"lydinchan1969", name:"Lý Dìn Chắn", g:"f", gen:16, spouses:["nguyenbichha1968"], years:"1969" },
  { id:"lethiaitrang1989", name:"Lê Thị Ái Trang", g:"f", gen:18, parents:["tan"], spouses:["lethanhtrung1983"], years:"1989" },
  { id:"lethanhtrung1983", name:"Lê Thành Trung", g:"m", gen:18, spouses:["lethiaitrang1989"], years:"1983" },
  { id:"phamthikimhong1981", name:"Phạm Thị Kim Hồng", g:"f", gen:18, parents:["tan"], spouses:["lehungsonduong1985"], years:"1981" },
  { id:"lehungsonduong1985", name:"Lê Hùng Sơn Dương", g:"m", gen:18, spouses:["phamthikimhong1981"], years:"1985" },
  { id:"nguyenbichly1995", name:"Nguyễn Bích Ly", g:"f", gen:17, parents:["nguyenbichha1968"], spouses:["nguyencaoson1995"], years:"1995" },
  { id:"nguyencaoson1995", name:"Nguyễn Cao Sơn", g:"m", gen:17, spouses:["nguyenbichly1995"], years:"1995" },
  { id:"nguyenletuonglan1977", name:"Nguyễn Lê Tường Lan", g:"f", gen:17, parents:["tan"], spouses:["nimchidung1972"], years:"1977" },
  { id:"nimchidung1972", name:"Nìm Chí Dũng", g:"m", gen:17, spouses:["nguyenletuonglan1977"], years:"1972" },
  { id:"nguyenlequochoang1980", name:"Nguyễn Lê Quốc Hoàng", g:"m", gen:17, parents:["tan"], spouses:["nguyenhoangminhthuy1984"], years:"1980" },
  { id:"nguyenhoangminhthuy1984", name:"Nguyễn Hoàng Minh Thúy", g:"f", gen:17, spouses:["nguyenlequochoang1980"], years:"1984" },
  { id:"lequangthinh1997", name:"Lê Quang Thịnh", g:"m", gen:17, parents:["phamthidiep1950"], years:"1997", note:"con Võ Thị Một 1968" },
  { id:"ludinhtri1988", name:"Lữ Đình Trí", g:"m", gen:18, parents:["tan"], spouses:["lethithanhthao1989"], years:"1988" },
  { id:"lethithanhthao1989", name:"Lê Thị Thanh Thảo", g:"f", gen:18, spouses:["ludinhtri1988"], years:"1989" },
  { id:"buivanthach1990", name:"Bùi Văn Thạch", g:"m", gen:18, parents:["tan"], spouses:["hoangthinhungoc1988"], years:"1990" },
  { id:"hoangthinhungoc1988", name:"Hoàng Thị Như Ngọc", g:"f", gen:18, spouses:["buivanthach1990"], years:"1988" },
  { id:"buivanthao1993", name:"Bùi Văn Thảo", g:"m", gen:18, parents:["tan"], spouses:["buithichaudoan1997"], years:"1993" },
  { id:"buithichaudoan1997", name:"Bùi Thị Châu Đoan", g:"f", gen:18, spouses:["buivanthao1993"], years:"1997" },
  { id:"nguyendangduy1987", name:"Nguyễn Đăng Duy", g:"m", gen:18, parents:["tan"], spouses:["lethiphong1990"], years:"1987" },
  { id:"lethiphong1990", name:"Lê Thị Phòng", g:"f", gen:18, spouses:["nguyendangduy1987"], years:"1990" },
  { id:"caophamtuenam1995", name:"Cao Phạm Tuế Nam", g:"m", gen:18, parents:["tan"], spouses:["nguyenthibichtram1994"], years:"1995" },
  { id:"nguyenthibichtram1994", name:"Nguyễn Thị Bích Trâm", g:"f", gen:18, spouses:["caophamtuenam1995"], years:"1994" },
  { id:"lemytien1996", name:"Lê Mỹ Tiến", g:"m", gen:18, parents:["nguyenbichly1995"], spouses:["nguyenthikimthoa1997"], years:"1996" },
  { id:"nguyenthikimthoa1997", name:"Nguyễn Thị Kim Thoa", g:"f", gen:18, spouses:["lemytien1996"], years:"1997" },
  { id:"buithidiem1985", name:"Bùi Thị Diễm", g:"f", gen:18, parents:["tan"], spouses:["lesonkhanh1984"], years:"1985" },
  { id:"lesonkhanh1984", name:"Lê Sơn Khánh", g:"m", gen:18, spouses:["buithidiem1985"], years:"1984" },
  { id:"lethituyen1984", name:"Lê Thị Tuyền", g:"f", gen:17, parents:["lequangtoan1954"], spouses:["truongxuanquang1973"], years:"1984" },
  { id:"truongxuanquang1973", name:"Trương Xuân Quang", g:"m", gen:17, spouses:["lethituyen1984"], years:"1973" },
  { id:"lethimydung1962", name:"Lê Thị Mỹ Dung", g:"f", gen:16, parents:["lequangtai1927"], years:"1962" },
  { id:"lethianhthi1990", name:"Lê Thị Anh Thi", g:"f", gen:17, parents:["lequangtoan1954"], spouses:["nguyenanhkhoa1990"], years:"1990" },
  { id:"nguyenanhkhoa1990", name:"Nguyễn Anh Khoa", g:"m", gen:17, spouses:["lethianhthi1990"], years:"1990" },
  { id:"nguyenlequoccuongx", name:"Nguyễn Lê Quốc Cường", g:"m", gen:17, parents:["lequangcong1957"], spouses:["phamthisau1982"] },
  { id:"phamthisau1982", name:"Phạm Thị Sáu", g:"f", gen:17, spouses:["nguyenlequoccuongx"], years:"1982" },
  { id:"tonthatduy1982", name:"Tôn Thất Duy", g:"m", gen:17, parents:["lequangngon1966"], spouses:["nguyenthithanhquy1985"], years:"1982" },
  { id:"nguyenthithanhquy1985", name:"Nguyễn Thị Thanh Quý", g:"f", gen:17, spouses:["tonthatduy1982"], years:"1985" },
  { id:"leanhthu1986", name:"Lê Anh Thư", g:"f", gen:17, parents:["tan"], spouses:["nguyenquocminh1980"], years:"1986" },
  { id:"nguyenquocminh1980", name:"Nguyễn Quốc Minh", g:"m", gen:17, spouses:["leanhthu1986"], years:"1980" },
  { id:"phamthithuha1984", name:"Phạm Thị Thu Hà", g:"f", gen:18, parents:["leanhthu1986"], spouses:["nguyenhanhy1985"], years:"1984" },
  { id:"nguyenhanhy1985", name:"Nguyễn Hân Hy", g:"m", gen:18, spouses:["phamthithuha1984"], years:"1985" },
  { id:"luthiaitruyen1984", name:"Lữ Thị Ái Truyền", g:"f", gen:18, parents:["tan"], spouses:["nguyenphuloc1982"], years:"1984" },
  { id:"nguyenphuloc1982", name:"Nguyễn Phú Lộc", g:"m", gen:18, spouses:["luthiaitruyen1984"], years:"1982" },
  { id:"phanthaikhuong1985", name:"Phan Thái Khương", g:"f", gen:18, parents:["tan"], spouses:["nguyenvanchi1978"], years:"1985" },
  { id:"nguyenvanchi1978", name:"Nguyễn Văn Chí", g:"m", gen:18, spouses:["phanthaikhuong1985"], years:"1978" },
  { id:"lethithao1986", name:"Lê Thị Thảo", g:"f", gen:17, parents:["lequangtoan1954"], spouses:["lequangphuong1986"], years:"1986" },
  { id:"lequangphuong1986", name:"Lê Quang Phương", g:"m", gen:17, spouses:["lethithao1986"], years:"1986" },
  { id:"phamlekhoa1986", name:"Phạm Lê Khoa", g:"m", gen:17, parents:["lethituongvy1954"], spouses:["trinhthithanhthao1986"], years:"1986" },
  { id:"trinhthithanhthao1986", name:"Trịnh Thị Thanh Thảo", g:"f", gen:17, spouses:["phamlekhoa1986"], years:"1986" },
  { id:"lethuvan1989", name:"Lê Thu Vân", g:"f", gen:17, parents:["tan"], spouses:["phuongtrangcuong1972"], years:"1989" },
  { id:"phuongtrangcuong1972", name:"Phương Tráng Cường", g:"m", gen:17, spouses:["lethuvan1989"], years:"1972" },
  { id:"phamtanhung1985", name:"Phạm Tấn Hùng", g:"m", gen:18, parents:["lethuvan1989"], spouses:["lethiminhthuy1985"], years:"1985" },
  { id:"lethiminhthuy1985", name:"Lê Thị Minh Thùy", g:"f", gen:18, spouses:["phamtanhung1985"], years:"1985" },
  { id:"luthiaitram1982", name:"Lữ Thị Ái Trâm", g:"f", gen:18, parents:["tan"], spouses:["ngolang1981"], years:"1982" },
  { id:"ngolang1981", name:"Ngô Lăng", g:"m", gen:18, spouses:["luthiaitram1982"], years:"1981" },
  { id:"phamthicamtrinh1983", name:"Phạm Thị Cẩm Trinh", g:"f", gen:17, parents:["lethihue1956"], years:"1983" },
  { id:"buiphilong2023", name:"Bùi Phi Long", g:"m", gen:19, parents:["buivanthao1993"], years:"2023" },
  { id:"nguyenphamphuongthao2023", name:"Nguyễn Phạm Phương Thảo", g:"f", gen:19, parents:["tan"], years:"2023" },
  { id:"nguyenthaiphuongnghi2011", name:"Nguyễn Thái Phương Nghi", g:"f", gen:19, parents:["phanthaikhuong1985"], years:"2011" },
  { id:"nguyenbichhien1971", name:"Nguyễn Bích Hiền", g:"m", gen:16, parents:["lethihaiduongx"], years:"1971" },
  { id:"nguyenlebaokhang2019", name:"Nguyễn Lê Bảo Khang", g:"m", gen:19, parents:["phamthikimhong1981"], years:"2019" },
  { id:"nguyenphuthinh2009", name:"Nguyễn Phú Thịnh", g:"m", gen:19, parents:["luthiaitram1982"], years:"2009" },
  { id:"phamleannhien2020", name:"Phạm Lê An Nhiên", g:"f", gen:19, parents:["tan"], years:"2020" },
  { id:"truongminhquan2012", name:"Trương Minh Quân", g:"m", gen:19, parents:["phamthikimhong1981"], years:"2012" },
  { id:"phamngocchinh1947", name:"Phạm Ngọc Chính", g:"m", gen:16, parents:["lequangtai1927"], years:"1947–1973" },
  { id:"nguyenquanghai1980", name:"Nguyễn Quang Hải", g:"m", gen:16, parents:["lethihaiduongx"], years:"1980–2001" },
  { id:"truongchauanh2014", name:"Trương Châu Anh", g:"f", gen:19, parents:["phamthikimhong1981"], years:"2014" },
  { id:"lequangtuan2006", name:"Lê Quang Tuấn", g:"m", gen:17, parents:["phamthithanhcan1957"], years:"2006" },
  { id:"lephuongnhi2024", name:"Lê Phương Nhi", g:"f", gen:19, parents:["phamthikimhong1981"], years:"2024" },
  { id:"phamlethuhang2014", name:"Phạm Lê Thu Hằng", g:"f", gen:19, parents:["tan"], years:"2014" },
  { id:"ngocattien2022", name:"Ngô Cát Tiên", g:"f", gen:19, parents:["tan"], years:"2022" },
  { id:"nguyenxhuunguyen1985", name:"Nguyenx Hữu Nguyên", g:"m", gen:17, parents:["tathisuong1964"], years:"1985" },
  { id:"lequangkhiem2012", name:"Lê Quang Khiêm", g:"m", gen:17, parents:["phamthithanhhoa1962"], years:"2012" },
  { id:"caotrongnhan2015", name:"Cao Trọng Nhân", g:"m", gen:19, parents:["caophamtuenam1995"], years:"2015" },
  { id:"buithithuytrang1988", name:"Bùi Thị Thùy Trang", g:"f", gen:18, parents:["tan"], years:"1988" },
  { id:"nguyenthithuduyen1989", name:"Nguyễn Thị Thu Duyên", g:"f", gen:18, parents:["tan"], years:"1989" },
  { id:"caophamkhanhmai2003", name:"Cao Phạm Khánh Mai", g:"f", gen:18, parents:["tan"], years:"2003" },
  { id:"phamlekhai1989", name:"Phạm Lê Khải", g:"m", gen:17, parents:["lethituongvy1954"], years:"1989" },
  { id:"lethitrucanh2003", name:"Lê Thị Trúc Anh", g:"f", gen:17, parents:["phamthithanhcan1957"], years:"2003" },
  { id:"bachtangthang2000", name:"Bạch Tăng Thắng", g:"m", gen:17, parents:["bachlam1969"], years:"2000" },
  { id:"lenguyenbichthuy2007", name:"Lê Nguyễn Bích Thủy", g:"f", gen:17, parents:["nguyenbichhung1977"], years:"2007" },
  { id:"nguyenthithuhong2014", name:"Nguyễn Thị Thu Hồng", g:"f", gen:17, parents:["nguyenquanghai1980"], years:"2014" },
  { id:"bachgialinh2004", name:"Bạch Gia Linh", g:"m", gen:17, parents:["nguyenbichha1968"], years:"2004" },
  { id:"nguyenduyhuan1992", name:"Nguyễn Duy Huấn", g:"m", gen:17, parents:["tathisuong1964"], years:"1992" },
  { id:"nguyenduyhieu1993", name:"Nguyễn Duy Hiệu", g:"m", gen:17, parents:["bachlam1969"], years:"1993" },
  { id:"truongquykhiem2004", name:"Trương Quý Khiêm", g:"m", gen:17, parents:["lehoangyen1974"], years:"2004" },
  { id:"truonghoangquan2006", name:"Trương Hoàng Quân", g:"m", gen:17, parents:["lehoangyen1974"], years:"2006" },
  { id:"lephuonguyen2008", name:"Lê Phương Uyên", g:"f", gen:17, parents:["lequanglong1976"], years:"2008" },
  { id:"lephuongngoc2006", name:"Lê Phương Ngọc", g:"f", gen:17, parents:["lequanglong1976"], years:"2006" },
  { id:"nguyenhanhnguyen2012", name:"Nguyễn Hạnh Nguyên", g:"f", gen:19, parents:["luthiaitruyen1984"], years:"2012" },
  { id:"lequangvu1998", name:"Lê Quang Vũ", g:"m", gen:17, parents:["phamngocliem1954"], years:"1998" },
  { id:"nguyenlyquanghao1999", name:"Nguyễn Lý Quang Hào", g:"m", gen:17, parents:["nguyenbichhien1971"], years:"1999" },
  { id:"nguyenvanhao2008", name:"Nguyễn Văn Hảo", g:"m", gen:17, parents:["nguyenbichhung1977"], years:"2008" },
  { id:"lenguyenhongson2000", name:"Lê Nguyễn Hồng Sơn", g:"m", gen:17, parents:["nguyenbichvan1975"], years:"2000" },
  { id:"lequangkhoi2016", name:"Lê Quang Khôi", g:"m", gen:17, parents:["lequanglong1976"], years:"2016" },
  { id:"lequangkhai2019", name:"Lê Quang Khải", g:"m", gen:17, parents:["tathisuong1964"], years:"2019" },
  { id:"phamtanhiep1993", name:"Phạm Tấn Hiệp", g:"m", gen:18, parents:["lequangvu1998"], years:"1993" },
  { id:"phamthihao1989", name:"Phạm Thị Hảo", g:"f", gen:18, parents:["lequangthinh1997"], years:"1989" },
  { id:"phanhoangthuc1980", name:"Phan Hoàng Thục", g:"f", gen:18, parents:["lethitrucanh2003"], years:"1980" },
  { id:"phanngocdao1982", name:"Phan Ngọc Dao", g:"f", gen:18, parents:["lethitrucanh2003"], years:"1982" },
  { id:"phamtanhiep1993_2", name:"Phạm Tấn Hiệp", g:"m", gen:18, parents:["lequangkhiem2012"], years:"1993" },
  { id:"phamtanhiep1993_3", name:"Phạm Tấn Hiệp", g:"m", gen:18, parents:["lequangkhiem2012"], years:"1993" },
  { id:"lemyphong1999", name:"Lê Mỹ Phong", g:"m", gen:18, parents:["nguyenbichly1995"], years:"1999" },
  { id:"nguyenlethanh1972", name:"Nguyễn Lê Thành", g:"m", gen:17, parents:["lethikimtuyen1955"], years:"1972" },
  { id:"tonthatquang1985", name:"Tôn Thất Quang", g:"m", gen:17, parents:["lequanghanh1968"], years:"1985–2002" },
  { id:"lephuonguyen2017", name:"Lê Phương Uyên", g:"f", gen:19, parents:["phamthikimhong1981"], years:"2017" },
  { id:"nguyenkimhang2006", name:"Nguyễn Kim Hằng", g:"f", gen:19, parents:["phamthikimhong1981"], years:"2006" },
  { id:"nimkhanhvan2007", name:"Nìm Khánh Vân", g:"f", gen:19, parents:["phamthikimhong1981"], years:"2007" },
  { id:"tonnukhanhan2013", name:"Tôn Nữ Khánh An", g:"f", gen:19, parents:["phamthikimhong1981"], years:"2013" },
  { id:"tonnuduyan2019", name:"Tôn Nữ Duy An", g:"f", gen:19, parents:["phamthikimhong1981"], years:"2019" },
  { id:"lethihonganh2012", name:"Lê Thị Hồng Ánh", g:"f", gen:19, parents:["phamthikimhong1981"], years:"2012" },
  { id:"lephamtungan2014", name:"Lê Phạm Tú Ngân", g:"f", gen:19, parents:["phamthithuha1984"], years:"2014" },
  { id:"nguyenthanhngoc2019", name:"Nguyễn Thanh Ngọc", g:"f", gen:19, parents:["phamtanhung1985"], years:"2019" },
  { id:"caotronghieu2023", name:"Cao Trọng Hiếu", g:"m", gen:19, parents:["caophamkhanhmai2003"], years:"2023" },
  { id:"lequangtri2023", name:"Lê Quang Trí", g:"m", gen:19, parents:["phamthikimhong1981"], years:"2023" },
  { id:"phamquiangtriet2015", name:"Phạm Quiang Triết", g:"m", gen:19, parents:["phamthikimhong1981"], years:"2015" },
  { id:"nguyenquochung2009", name:"Nguyễn Quốc Hưng", g:"m", gen:19, parents:["phamthikimhong1981"], years:"2009" },
  { id:"nimhuankhanh2015", name:"Nìm Huân Khánh", g:"m", gen:19, parents:["phamthikimhong1981"], years:"2015" },
  { id:"nguyenphuckhanh2012", name:"Nguyễn Phúc Khánh", g:"m", gen:19, parents:["phamthikimhong1981"], years:"2012" },
  { id:"nguyenphuckhang2022", name:"Nguyễn Phúc Khang", g:"m", gen:19, parents:["phamthikimhong1981"], years:"2022" },
  { id:"nguyenbaongoc2015", name:"Nguyễn Bảo Ngọc", g:"m", gen:19, parents:["phamthikimhong1981"], years:"2015" },
  { id:"nguyenbaolong2015", name:"Nguyễn Bảo Long", g:"m", gen:19, parents:["phamthikimhong1981"], years:"2015" },
  { id:"phuongtegiabao2018", name:"Phương Tề Gia Bảo", g:"m", gen:19, parents:["phamthikimhong1981"], years:"2018" },
  { id:"leanhthu2017", name:"Lê Anh Thư", g:"m", gen:19, parents:["lethiaitrang1989"], years:"2017" },
  { id:"ledinhduyhieu2010", name:"Lê Đình Duy Hiếu", g:"m", gen:19, parents:["ludinhtri1988"], years:"2010" },
  { id:"ledinhduynhan2016", name:"Lê Đình Duy Nhân", g:"m", gen:19, parents:["ludinhtri1988"], years:"2016" },
  { id:"lekhanhmy2019", name:"Lê Khánh My", g:"f", gen:19, parents:["buithidiem1985"], years:"2019" },
  { id:"leanhquoc2014", name:"Lê Anh Quốc", g:"m", gen:19, parents:["lethiaitrang1989"], years:"2014" },
  { id:"lethinguyetmang1926", name:"Lê Thị Nguyệt Mãng", g:"f", gen:15, parents:["nhi"], spouses:["nguyendinhba1926"], years:"1926" },
  { id:"nguyendinhba1926", name:"Nguyễn Đình Ba", g:"m", gen:15, spouses:["lethinguyetmang1926"], years:"1926" },
  { id:"lethinguyetdinhvinh1928", name:"Lê Thị Nguyệt Dinh (Vinh)", g:"f", gen:15, parents:["nhi"], spouses:["trantuyen1923"], years:"1928" },
  { id:"trantuyen1923", name:"Trần Tuyên", g:"m", gen:15, spouses:["lethinguyetdinhvinh1928"], years:"1923" },
  { id:"lequangdan1931", name:"Lê Quang Dân", g:"m", gen:15, parents:["nhi"], spouses:["dothilocx"], years:"1931" },
  { id:"dothilocx", name:"Đỗ Thị Lộc", g:"f", gen:15, spouses:["lequangdan1931"] },
  { id:"lequangloc1934", name:"Lê Quang Lộc", g:"m", gen:15, parents:["nhi"], spouses:["phamthibichluu1942"], years:"1934" },
  { id:"phamthibichluu1942", name:"Phạm Thị Bích Lưu", g:"f", gen:15, spouses:["lequangloc1934"], years:"1942" },
  { id:"lethinguyetthat1940", name:"Lê Thị Nguyệt Thất", g:"f", gen:15, parents:["nhi"], years:"1940" },
  { id:"lequanglam1969", name:"Lê Quang Lâm", g:"m", gen:16, parents:["lequangloc1934"], spouses:["tranthithunhi1970"], years:"1969" },
  { id:"tranthithunhi1970", name:"Trần Thị Thu Nhị", g:"f", gen:16, spouses:["lequanglam1969"], years:"1970" },
  { id:"nguyentuanphong1994", name:"Nguyễn Tuấn Phong", g:"m", gen:18, parents:["nhi"], spouses:["lethihao1993"], years:"1994" },
  { id:"lethihao1993", name:"Lê Thị Hào", g:"f", gen:18, spouses:["nguyentuanphong1994"], years:"1993" },
  { id:"lethithuyhien1968", name:"Lê Thị Thúy Hiền", g:"f", gen:17, parents:["nhi"], spouses:["nguyenphucuong1960"], years:"1968" },
  { id:"nguyenphucuong1960", name:"Nguyễn Phú Cường", g:"m", gen:17, spouses:["lethithuyhien1968"], years:"1960" },
  { id:"nguyenduyquynhanh2002", name:"Nguyễn Duy Quỳnh Anh", g:"f", gen:18, parents:["nhi"], years:"2002" },
  { id:"nguyenthitinh1952", name:"Nguyễn Thị Tính", g:"f", gen:16, parents:["lethinguyetmang1926"], spouses:["barryrandallturnel1943"], years:"1952" },
  { id:"barryrandallturnel1943", name:"Barry Randall Turnel", g:"m", gen:16, spouses:["nguyenthitinh1952"], years:"1943–2023" },
  { id:"nguyenthiminhtam1947", name:"Nguyễn Thị Minh Tâm", g:"f", gen:16, parents:["lethinguyetmang1926"], spouses:["lehoang1939"], years:"1947" },
  { id:"lehoang1939", name:"Lê Hoàng", g:"m", gen:16, spouses:["nguyenthiminhtam1947"], years:"1939–1984" },
  { id:"tranngocthuan1967", name:"Trần Ngọc Thuận", g:"m", gen:16, parents:["lethinguyetdinhvinh1928"], years:"1967–1973" },
  { id:"tranthithuha1955", name:"Trần Thị Thu Hà", g:"f", gen:16, parents:["lethinguyetdinhvinh1928"], spouses:["phamthephuong1949"], years:"1955" },
  { id:"phamthephuong1949", name:"Phạm Thế Phương", g:"m", gen:16, spouses:["tranthithuha1955"], years:"1949" },
  { id:"lequangnghia1978", name:"Lê Quang Nghĩa", g:"m", gen:16, parents:["lequangdan1931"], spouses:["nguyenthithusuong1981"], years:"1978" },
  { id:"nguyenthithusuong1981", name:"Nguyễn Thị Thu Sương", g:"f", gen:16, spouses:["lequangnghia1978"], years:"1981" },
  { id:"lethihongly1977", name:"Lê Thị Hồng Lý", g:"f", gen:16, parents:["lequangdan1931"], spouses:["leanhtai1968"], years:"1977" },
  { id:"leanhtai1968", name:"Lê Anh Tài", g:"m", gen:16, spouses:["lethihongly1977"], years:"1968" },
  { id:"lequangminhhuy1971", name:"Lê Quang Minh (Huy)", g:"m", gen:16, parents:["nhi"], spouses:["nguyenquocthutram1973"], years:"1971" },
  { id:"nguyenquocthutram1973", name:"Nguyễn Quốc Thư Trâm", g:"f", gen:16, spouses:["lequangminhhuy1971"], years:"1973" },
  { id:"lekieuhanh1970", name:"Lê Kiều Hạnh", g:"f", gen:17, parents:["nguyenthiminhtam1947"], spouses:["nguyenduyduc1969"], years:"1970" },
  { id:"nguyenduyduc1969", name:"Nguyễn Duy Đức", g:"m", gen:17, spouses:["lekieuhanh1970"], years:"1969" },
  { id:"ledongho1974", name:"Lê Đông Hồ", g:"m", gen:17, parents:["nguyenthitinh1952"], spouses:["hoangthivankhanh1981"], years:"1974" },
  { id:"hoangthivankhanh1981", name:"Hoàng Thị Vân Khánh", g:"f", gen:17, spouses:["ledongho1974"], years:"1981" },
  { id:"lethibichhoai1977", name:"Lê Thị Bích Hoài", g:"f", gen:17, parents:["nguyenthitinh1952"], spouses:["caohoangngoc1960"], years:"1977" },
  { id:"caohoangngoc1960", name:"Cao Hoàng Ngọc", g:"m", gen:17, spouses:["lethibichhoai1977"], years:"1960" },
  { id:"lemanhhao1972", name:"Lê Mạnh Hào", g:"m", gen:17, parents:["nguyenthitinh1952"], spouses:["nguyenanhdao1976"], years:"1972" },
  { id:"nguyenanhdao1976", name:"Nguyễn Anh Đào", g:"f", gen:17, spouses:["lemanhhao1972"], years:"1976" },
  { id:"phamtranphuonganh1979", name:"Phạm Trần Phương Anh", g:"f", gen:17, parents:["tranthithuha1955"], spouses:["tranquocbao1976"], years:"1979" },
  { id:"tranquocbao1976", name:"Trần Quốc Bảo", g:"m", gen:17, spouses:["phamtranphuonganh1979"], years:"1976" },
  { id:"phamtranphuonganh1982", name:"Phạm Trần Phương Ánh", g:"f", gen:17, parents:["tranngocthuan1967"], years:"1982" },
  { id:"phamthephong1989", name:"Phạm Thế Phong", g:"m", gen:17, parents:["tranngocthuan1967"], spouses:["tranthithanhtrang1993"], years:"1989" },
  { id:"tranthithanhtrang1993", name:"Trần Thị Thanh Trang", g:"f", gen:17, spouses:["phamthephong1989"], years:"1993" },
  { id:"ledaquynh2000", name:"Lê Dạ Quỳnh", g:"f", gen:17, parents:["lethihongly1977"], years:"2000" },
  { id:"lekimkhanh2006", name:"Lê Kim Khánh", g:"f", gen:17, parents:["lequangnghia1978"], years:"2006" },
  { id:"lequangkhoi2024", name:"Lê Quang Khôi", g:"m", gen:17, parents:["lequangnghia1978"], years:"2024" },
  { id:"lethiquynhchau1993", name:"Lê Thị Quỳnh Châu", g:"f", gen:17, parents:["lequanglam1969"], spouses:["jonathanbrown1981"], years:"1993" },
  { id:"jonathanbrown1981", name:"Jonathan Brown", g:"m", gen:17, spouses:["lethiquynhchau1993"], years:"1981" },
  { id:"lequanglong2000", name:"Lê Quang Long", g:"m", gen:17, parents:["lequanglam1969"], years:"2000" },
  { id:"lequanganh1999", name:"Lê Quang Anh", g:"m", gen:17, parents:["lequangminhhuy1971"], years:"1999–2009" },
  { id:"lequangbao2003", name:"Lê Quang Bảo", g:"m", gen:17, parents:["lequangminhhuy1971"], years:"2003" },
  { id:"leminhthu2010", name:"Lê Minh Thư", g:"f", gen:17, parents:["lequangminhhuy1971"], years:"2010" },
  { id:"nguyenduytrung2003", name:"Nguyễn Duy Trung", g:"m", gen:18, parents:["lemanhhao1972"], years:"2003" },
  { id:"lehoangkhoa2009", name:"Lê Hoàng Khoa", g:"m", gen:18, parents:["ledongho1974"], years:"2009" },
  { id:"lehoangbach2016", name:"Lê Hoàng Bách", g:"m", gen:18, parents:["lethibichhoai1977"], years:"2016" },
  { id:"lehoangminh2006", name:"Lê Hoàng Minh", g:"m", gen:18, parents:["phamtranphuonganh1979"], years:"2006" },
  { id:"lehoangkhanhngan2012", name:"Lê Hoàng Khánh Ngân", g:"f", gen:18, parents:["phamtranphuonganh1982"], years:"2012" },
  { id:"caohoangtien2006", name:"Cao Hoàng Tiến", g:"m", gen:18, parents:["phamthephong1989"], years:"2006" },
  { id:"caohoangkimngan2012", name:"Cao Hoàng Kim Ngân", g:"f", gen:18, parents:["phamthephong1989"], years:"2012" },
  { id:"trannguyenphusi2005", name:"Trần Nguyễn Phú Sĩ", g:"m", gen:18, parents:["ledaquynh2000"], years:"2005" },
  { id:"trannguyenphuhung2008", name:"Trần Nguyễn Phú Hưng", g:"m", gen:18, parents:["lekimkhanh2006"], years:"2008" },
  { id:"phamnhathao2023", name:"Phạm Nhật Hào", g:"m", gen:18, parents:["lequangkhoi2024"], years:"2023" },
  { id:"lequangutx", name:"Lê Quang Út", g:"m", gen:15, parents:["nhi"], spouses:["mattunhox"] },
  { id:"mattunhox", name:"Mất từ nhỏ", g:"f", gen:15, spouses:["lequangutx"] },
  { id:"mattunhox_2", name:"Mất từ nhỏ", g:"m", gen:15, parents:["nhi"] },
  { id:"mattunhox_3", name:"Mất từ nhỏ", g:"m", gen:15, parents:["nhi"] },
  { id:"mattunhox_4", name:"Mất từ nhỏ", g:"m", gen:15, parents:["nhi"] },
  { id:"mattunhox_5", name:"Mất từ nhỏ", g:"m", gen:15, parents:["nhi"] },
  { id:"mattunhox_6", name:"Mất từ nhỏ", g:"m", gen:15, parents:["nhi"] },
  { id:"lequangkiet1948", name:"Lê Quang Kiệt", g:"m", gen:15, parents:["tam"], years:"1948" },
  { id:"lequangdungx", name:"Lê Quang Dũng", g:"m", gen:15, parents:["tam"], spouses:["huynhthihoax"] },
  { id:"huynhthihoax", name:"Huỳnh Thị Hoa", g:"f", gen:15, spouses:["lequangdungx"] },
  { id:"lequangtuyenx", name:"Lê Quang Tuyên", g:"m", gen:15, parents:["tam"], spouses:["nguyenthisenx"] },
  { id:"nguyenthisenx", name:"Nguyễn Thị Sen", g:"f", gen:15, spouses:["lequangtuyenx"] },
  { id:"lequangtuanx", name:"Lê Quang Tuấn", g:"m", gen:15, parents:["tam"], spouses:["nguyenthidieukimx"] },
  { id:"nguyenthidieukimx", name:"Nguyễn Thị Diệu Kim", g:"f", gen:15, spouses:["lequangtuanx"] },
  { id:"lequanghungx", name:"Lê Quang Hùng", g:"m", gen:15, parents:["tam"], spouses:["phamthingocanhx"] },
  { id:"phamthingocanhx", name:"Phạm Thị Ngọc Anh", g:"f", gen:15, spouses:["lequanghungx"] },
  { id:"lethinguyetx", name:"Lê Thị Nguyệt", g:"f", gen:15, parents:["tam"], spouses:["doanvanchuongx"] },
  { id:"doanvanchuongx", name:"Đoàn Văn Chương", g:"m", gen:15, spouses:["lethinguyetx"] },
  { id:"lethihuu1937", name:"Lê Thị Hữu", g:"f", gen:15, parents:["tam"], spouses:["chetrung1937"], years:"1937" },
  { id:"chetrung1937", name:"Chế Trung", g:"m", gen:15, spouses:["lethihuu1937"], years:"1937" },
  { id:"lequangbe1934", name:"Lê Quang Bé", g:"m", gen:15, parents:["tam"], years:"1934" },
  { id:"lequangman1984", name:"Lê Quang Mẫn", g:"m", gen:16, parents:["lequangtuyenx"], spouses:["buithianhtuyet1990"], years:"1984" },
  { id:"buithianhtuyet1990", name:"Bùi Thị Ánh Tuyết", g:"f", gen:16, spouses:["lequangman1984"], years:"1990" },
  { id:"lehuynhquangvu1998", name:"Lê Huỳnh Quang Vũ", g:"m", gen:16, parents:["lequangdungx"], years:"1998" },
  { id:"lehuynhquanghau1995", name:"Lê Huỳnh Quang Hậu", g:"m", gen:16, parents:["lequangdungx"], years:"1995" },
  { id:"lequangtung1983", name:"Lê Quang Tùng", g:"m", gen:16, parents:["lequanghungx"], spouses:["damthithanhhieu1987"], years:"1983" },
  { id:"damthithanhhieu1987", name:"Đảm Thị Thanh Hiếu", g:"f", gen:16, spouses:["lequangtung1983"], years:"1987" },
  { id:"lethimy1987", name:"Lê Thị My", g:"f", gen:16, parents:["lequangtuyenx"], spouses:["nguyendinhnhan1977"], years:"1987" },
  { id:"nguyendinhnhan1977", name:"Nguyễn Đình Nhân", g:"m", gen:16, spouses:["lethimy1987"], years:"1977" },
  { id:"letimuoi1993", name:"Lê Tỉ Muội", g:"f", gen:16, parents:["lequangtuyenx"], spouses:["nguyentringhia1991"], years:"1993" },
  { id:"nguyentringhia1991", name:"Nguyễn Trí Nghĩa", g:"m", gen:16, spouses:["letimuoi1993"], years:"1991" },
  { id:"lenguyenquynhnhu1974", name:"Lê Nguyễn Quỳnh Như", g:"f", gen:16, parents:["lequangtuanx"], spouses:["nguyenxuanthong1974"], years:"1974" },
  { id:"nguyenxuanthong1974", name:"Nguyễn Xuân Thông", g:"m", gen:16, spouses:["lenguyenquynhnhu1974"], years:"1974" },
  { id:"lethianhhoang1980", name:"Lê Thị Anh Hoàng", g:"f", gen:16, parents:["lequanghungx"], spouses:["huynhngocthi1979"], years:"1980" },
  { id:"huynhngocthi1979", name:"Huỳnh Ngọc Thi", g:"m", gen:16, spouses:["lethianhhoang1980"], years:"1979" },
  { id:"lethianhdao1992", name:"Lê Thị Anh Đào", g:"f", gen:16, parents:["lequanghungx"], spouses:["dophucuong1992"], years:"1992" },
  { id:"dophucuong1992", name:"Đỗ Phú Cường", g:"m", gen:16, spouses:["lethianhdao1992"], years:"1992" },
  { id:"lethianhthu1978", name:"Lê Thị Anh Thư", g:"f", gen:16, parents:["lequanghungx"], spouses:["nguyenbaphung1977"], years:"1978" },
  { id:"nguyenbaphung1977", name:"Nguyễn Bá Phùng", g:"m", gen:16, spouses:["lethianhthu1978"], years:"1977" },
  { id:"doanlehung1970", name:"Đoàn Lê Hưng", g:"m", gen:16, parents:["lethinguyetx"], spouses:["nguyenthiaithu1974"], years:"1970" },
  { id:"nguyenthiaithu1974", name:"Nguyễn Thị Ái Thu", g:"f", gen:16, spouses:["doanlehung1970"], years:"1974" },
  { id:"lenguyenquangdiem1971", name:"Lê Nguyễn Quang Điềm", g:"m", gen:16, parents:["lequangtuanx"], spouses:["lethibichngoc1972"], years:"1971" },
  { id:"lethibichngoc1972", name:"Lê Thị Bích Ngọc", g:"f", gen:16, spouses:["lenguyenquangdiem1971"], years:"1972" },
  { id:"chelephat1961", name:"Chế Lê Phát", g:"m", gen:16, parents:["lequangbe1934"], spouses:["nguyenthingocanh1968"], years:"1961" },
  { id:"nguyenthingocanh1968", name:"Nguyễn Thị Ngọc Ánh", g:"f", gen:16, spouses:["chelephat1961"], years:"1968" },
  { id:"chelethuong1960", name:"Chế Lê Thương", g:"f", gen:16, parents:["lequangbe1934"], spouses:["tranvanhanh1959"], years:"1960" },
  { id:"tranvanhanh1959", name:"Trần Văn Hạnh", g:"m", gen:16, spouses:["chelethuong1960"], years:"1959" },
  { id:"doanledieuchi1972", name:"Đoàn Lê Diệu Chi", g:"f", gen:16, parents:["lethinguyetx"], spouses:["rankonenjohnmichel1966"], years:"1972" },
  { id:"rankonenjohnmichel1966", name:"Rankonen John Michel", g:"m", gen:16, spouses:["doanledieuchi1972"], years:"1966" },
  { id:"doanlecong1974", name:"Đoàn Lê Công", g:"m", gen:16, parents:["lethinguyetx"], spouses:["tranthimynu1980"], years:"1974" },
  { id:"tranthimynu1980", name:"Trần Thị Mỹ Nữ", g:"f", gen:16, spouses:["doanlecong1974"], years:"1980" },
  { id:"doanlephung1978", name:"Đoàn Lê Phụng", g:"m", gen:16, parents:["lethinguyetx"], years:"1978" },
  { id:"lenguyenquangminh1972", name:"Lê Nguyễn Quang Minh", g:"m", gen:16, parents:["lequangtuanx"], spouses:["phamthianhphuong1964"], years:"1972" },
  { id:"phamthianhphuong1964", name:"Phạm Thị ÁNh Phượng", g:"f", gen:16, spouses:["lenguyenquangminh1972"], years:"1964" },
  { id:"lenguyenquanglong1985", name:"Lê Nguyễn Quang Long", g:"m", gen:16, parents:["lequangtuanx"], spouses:["nguyenthibichloan1986"], years:"1985" },
  { id:"nguyenthibichloan1986", name:"Nguyễn Thị Bích Loan", g:"f", gen:16, spouses:["lenguyenquanglong1985"], years:"1986" },
  { id:"chethileduyen1964", name:"Chế Thị Lê Duyên", g:"f", gen:16, parents:["lequangbe1934"], spouses:["trinhvanhai1963"], years:"1964" },
  { id:"trinhvanhai1963", name:"Trịnh Văn Hải", g:"m", gen:16, spouses:["chethileduyen1964"], years:"1963" },
  { id:"chelephuc1963", name:"Chế Lê Phúc", g:"m", gen:16, parents:["lequangbe1934"], spouses:["nguyenthithanhnga1960"], years:"1963" },
  { id:"nguyenthithanhnga1960", name:"Nguyễn Thị Thanh Nga", g:"f", gen:16, spouses:["chelephuc1963"], years:"1960" },
  { id:"tranngocquang1991", name:"Trần Ngọc Quang", g:"m", gen:17, parents:["chelephat1961"], spouses:["ngothimyvan1991"], years:"1991" },
  { id:"ngothimyvan1991", name:"Ngô Thị Mỹ Vân", g:"f", gen:17, spouses:["tranngocquang1991"], years:"1991" },
  { id:"chelequynhuyen1975", name:"Chế Lê Quỳnh Uyên", g:"f", gen:16, parents:["lethihuu1937"], spouses:["tranvanthuan1974"], years:"1975" },
  { id:"tranvanthuan1974", name:"Trần Văn Thuận", g:"m", gen:16, spouses:["chelequynhuyen1975"], years:"1974" },
  { id:"chelephu1967", name:"Chế Lê Phú", g:"m", gen:16, parents:["lequangbe1934"], spouses:["nguyenngockimtram1972"], years:"1967" },
  { id:"nguyenngockimtram1972", name:"Nguyễn Ngọc Kim Trâm", g:"f", gen:16, spouses:["chelephu1967"], years:"1972" },
  { id:"chelequynhlien1969", name:"Chế Lê Quỳnh Liên", g:"f", gen:16, parents:["lethihuu1937"], spouses:["buihakhai1967"], years:"1969" },
  { id:"buihakhai1967", name:"Bùi Hạ Khai", g:"m", gen:16, spouses:["chelequynhlien1969"], years:"1967" },
  { id:"chelephuong1971", name:"Chế Lê Phương", g:"m", gen:16, parents:["lethihuu1937"], spouses:["nguyenthinu1972"], years:"1971" },
  { id:"nguyenthinu1972", name:"Nguyễn Thị Nữ", g:"f", gen:16, spouses:["chelephuong1971"], years:"1972" },
  { id:"tranngocvinh1986", name:"Trần Ngọc Vinh", g:"m", gen:17, parents:["chelethuong1960"], spouses:["nguyenthithanhthuy1986"], years:"1986" },
  { id:"nguyenthithanhthuy1986", name:"Nguyễn Thị Thanh Thủy", g:"f", gen:17, spouses:["tranngocvinh1986"], years:"1986" },
  { id:"chelephi1977", name:"Chế Lê Phi", g:"m", gen:16, parents:["lethihuu1937"], spouses:["nguyenthithanhthuy1984"], years:"1977" },
  { id:"nguyenthithanhthuy1984", name:"Nguyễn Thị Thanh Thúy", g:"f", gen:16, spouses:["chelephi1977"], years:"1984" },
  { id:"trinhhailinh1996", name:"Trịnh Hải Linh", g:"f", gen:17, parents:["chelequynhuyen1975"], spouses:["nguyenchitrung1996"], years:"1996" },
  { id:"nguyenchitrung1996", name:"Nguyễn Chí Trung", g:"m", gen:17, spouses:["trinhhailinh1996"], years:"1996" },
  { id:"trinhquanghuy1986", name:"Trịnh Quang Huy", g:"m", gen:17, parents:["chelephuong1971"], spouses:["ngothihien1992"], years:"1986" },
  { id:"ngothihien1992", name:"Ngô Thị Hiền", g:"f", gen:17, spouses:["trinhquanghuy1986"], years:"1992" },
  { id:"chenguyenha1992", name:"Chế Nguyên Hạ", g:"f", gen:17, parents:["chelephu1967"], spouses:["tranquangvinh1995"], years:"1992" },
  { id:"tranquangvinh1995", name:"Trân Quang Vinh", g:"m", gen:17, spouses:["chenguyenha1992"], years:"1995" },
  { id:"trannguyenannam2018", name:"Trần Nguyễn An Nam", g:"m", gen:18, parents:["tranngocvinh1986"], years:"2018" },
  { id:"chenguyenkha1995", name:"Chế Nguyên Kha", g:"m", gen:17, parents:["doanlehung1970"], spouses:["phamthibichngoc1996"], years:"1995" },
  { id:"phamthibichngoc1996", name:"Phạm Thị Bích Ngọc", g:"f", gen:17, spouses:["chenguyenkha1995"], years:"1996" },
  { id:"nguyendinhhieunghia2015", name:"Nguyễn Đình Hiếu Nghĩa", g:"m", gen:17, parents:["lethimy1987"], years:"2015" },
  { id:"nguyenlehoaiphuong2001", name:"Nguyễn Lê Hoài Phương", g:"f", gen:17, parents:["lenguyenquanglong1985"], years:"2001" },
  { id:"chelamvien1995", name:"Chế Lâm Viên", g:"m", gen:17, parents:["chelequynhlien1969"], years:"1995" },
  { id:"nguyenlethaonhi2008", name:"Nguyễn Lê Thảo Nhi", g:"f", gen:17, parents:["lenguyenquanglong1985"], years:"2008" },
  { id:"trananhkhoax", name:"Trần Anh Khoa", g:"m", gen:18, parents:["tranngocquang1991"] },
  { id:"tranphucanx", name:"Trần Phúc An", g:"m", gen:18, parents:["chenguyenha1992"] },
  { id:"doannguyenxuanquynh1999", name:"Đoàn Nguyễn Xuân Quỳnh", g:"f", gen:17, parents:["doanlephung1978"], years:"1999" },
  { id:"lenguyengiahan2017", name:"Lê Nguyễn Gia Hân", g:"f", gen:17, parents:["lethianhthu1978"], years:"2017" },
  { id:"lekhanhngan2022", name:"Lê Khánh Ngân", g:"f", gen:17, parents:["lequangman1984"], years:"2022" },
  { id:"nguyendinhhieukien2017", name:"Nguyễn Đình Hiếu Kiên", g:"m", gen:17, parents:["lethimy1987"], years:"2017" },
  { id:"nguyenngocyenlam2024", name:"Nguyễn NGọc Yên Lam", g:"f", gen:17, parents:["letimuoi1993"], years:"2024" },
  { id:"nguyencaominhan2019", name:"Nguyễn Cao Minh An", g:"m", gen:17, parents:["letimuoi1993"], years:"2019" },
  { id:"nguyenlebaotram2011", name:"Nguyễn Lê Bảo Trâm", g:"f", gen:17, parents:["lethianhthu1978"], years:"2011" },
  { id:"nguyenlenguyen2014", name:"Nguyễn Lê Nguyên", g:"m", gen:17, parents:["lethianhthu1978"], years:"2014" },
  { id:"huynhminhtriet2023", name:"Huỳnh Minh Triết", g:"m", gen:17, parents:["lequangtung1983"], years:"2023" },
  { id:"lebaongan2018", name:"Lê Bảo Ngân", g:"f", gen:17, parents:["lethianhdao1992"], years:"2018" },
  { id:"chequynhphuongthao1993", name:"Chế Quỳnh Phương Thảo", g:"f", gen:17, parents:["chelephuc1963"], years:"1993" },
  { id:"tranngoctoan1995", name:"Trần Ngọc Toàn", g:"m", gen:17, parents:["chelephuc1963"], years:"1995" },
  { id:"doannguyennhuquynh2008", name:"Đoàn Nguyễn Như Quỳnh", g:"f", gen:17, parents:["doanlephung1978"], years:"2008" },
  { id:"lequanghoa2017", name:"Lê Quang Hòa", g:"m", gen:17, parents:["lequangman1984"], years:"2017" },
  { id:"chenguyen1999", name:"Chế Nguyên", g:"m", gen:17, parents:["chethileduyen1964"], years:"1999" },
  { id:"lequangduy2013", name:"Lê Quang Duy", g:"m", gen:17, parents:["lequangtung1983"], years:"2013" },
  { id:"lebichhuyen2006", name:"Lê Bích Huyền", g:"f", gen:17, parents:["lenguyenquanglong1985"], years:"2006" },
  { id:"lenguyenquang2014", name:"Lê Nguyễn Quang", g:"m", gen:17, parents:["lethianhthu1978"], years:"2014" },
  { id:"trinhhailam2016", name:"Trịnh Hải Lâm", g:"m", gen:18, parents:["trinhquanghuy1986"], years:"2016" },
  { id:"nguyenlinhnha2023", name:"Nguyễn Linh Nhã", g:"f", gen:18, parents:["trinhhailinh1996"], years:"2023" },
  { id:"chenguyen2009", name:"Chế Nguyễn", g:"m", gen:17, parents:["chelephi1977"], years:"2009" },
  { id:"rankonenemilymichaela2014", name:"Rankonen Emily Michaela", g:"f", gen:17, parents:["lenguyenquangdiem1971"], years:"2014" },
  { id:"lebichtram1996", name:"Lê Bích Trâm", g:"f", gen:17, parents:["lenguyenquanglong1985"], years:"1996" },
  { id:"chenguyenkhang2004", name:"Chế Nguyên Khang", g:"f", gen:17, parents:["doanledieuchi1972"], years:"2004" },
  { id:"doandaivi2007", name:"Đoàn Đại Vi", g:"m", gen:17, parents:["lenguyenquangminh1972"], years:"2007" },
  { id:"huynhbaongoc2010", name:"Huỳnh Bảo Ngọc", g:"f", gen:17, parents:["lethianhhoang1980"], years:"2010" },
  { id:"huynhbaonhi2010", name:"Huỳnh Bảo Nhi", g:"f", gen:17, parents:["lethianhhoang1980"], years:"2010" },
  { id:"trinhlamkhoi2019", name:"Trịnh Lâm Khôi", g:"m", gen:18, parents:["trinhquanghuy1986"], years:"2019" },
  { id:"chequynhhan2001", name:"Chế Quỳnh Hân", g:"f", gen:17, parents:["chelephi1977"], years:"2001–2019" },
  { id:"votanthinh1995", name:"Võ Tấn Thịnh", g:"m", gen:17, parents:["doanlehung1970"], years:"1995" },
  { id:"buikhanhquynh1997", name:"Bùi Khánh Quỳnh", g:"f", gen:17, parents:["doanlehung1970"], years:"1997" },
  { id:"chenguyenhoangnam2011", name:"Chế Nguyễn Hoàng Nam", g:"m", gen:17, parents:["doanlecong1974"], years:"2011" },
  { id:"buistevendoan2000", name:"Bui Steven Doan", g:"m", gen:17, parents:["lenguyenquangdiem1971"], years:"2000" },
  { id:"doandaithang2018", name:"Đoàn Đại Thắng", g:"m", gen:17, parents:["lenguyenquynhnhu1974"], years:"2018" },
  { id:"doannhavy2012", name:"Đoàn Nhã Vy", g:"f", gen:17, parents:["lenguyenquangminh1972"], years:"2012" },
  { id:"trankhanhvan2005", name:"Trần Khánh Vân", g:"f", gen:17, parents:["doanledieuchi1972"], years:"2005" },
];
